### ISSUE TITLE
Add method to obtain the list of all packages

### ISSUE THREAD

**Issue by joaompinto** [repo-helper/pypi-json#16]
## Description
As a developer I would like to be able to obtain the list of all packages, similar to:

curl -H "Accept: application/vnd.pypi.simple.v1+json" https://pypi.org/simple/

**Comment by notatallshaw** [comment]
Isn't this library mostly a wrapper around these two JSON end points: https://warehouse.pypa.io/api-reference/json.html If so these is no way to look up what projects exist.

The simple API which you give an example of using it's recently added JSON format (PEP 691) can be accessed fairly simply using requests or the package `pypi-simple` which has a method for what you want: https://pypi-simple.readthedocs.io/en/stable/api.html#pypi_simple.PyPISimple.get_index_page

**Comment by joaompinto** [comment]
@notatallshaw I will close the issue on the assumption that indeed this lib is just a wrapper for json  endpoint.

PySimple JSON does not include the _last_serial meta data, so I guess I will need to stick with a custom http request.

I am trying to build an incremental pypi metadata mirror but can't find much info about this serial. I guess I will need to look at the source from https://bandersnatch.readthedocs.io/en/latest/ and try to get some help.

Thanks
